from od_detection import DetectOD
from image_reader import ImageReader
from image_processor import ImageProcessor
from blood_detection import ExtractBloodVessels
from regions_detect_knn import Labels, KNeighborsRegions